import { createGlobalStyle } from 'styled-components';

const TypographyStyle = createGlobalStyle`
/* #### Generated By: http://www.cufonfonts.com #### */
@font-face {
    font-family: 'Airbnb Cereal App Book';
    font-style: normal;
    font-weight: normal;
    src: local('Airbnb Cereal App Book'), url('/assets/fonts/airbnb/AirbnbCerealBook.woff') format('woff');
    }

    @font-face {
    font-family: 'Airbnb Cereal App Medium';
    font-style: normal;
    font-weight: normal;
    src: local('Airbnb Cereal App Medium'), url('/assets/fonts/airbnb/AirbnbCerealMedium.woff') format('woff');
    }

    @font-face {
    font-family: 'Airbnb Cereal App Bold';
    font-style: normal;
    font-weight: normal;
    src: local('Airbnb Cereal App Bold'), url('/assets/fonts/airbnb/AirbnbCerealBold.woff') format('woff');
    }

    body{
        font-family: 'Airbnb Cereal App Book';
        font-weight: normal;
        font-size: 16px;
    }
`

export default TypographyStyle